services:
  apialuno:
    build: ./APIA
    ports:
    - "3000:3000"
    enviroment:
    - APIB_URL=http://apiprofessor:3001
    networks:
    - apis-escola
  
  apiprofessor:
    build: ./APIB
    ports:
    - "3001:3001"
    enviroment:
    - APIA_URL=http://apialuno:3000
    networks:
    - apis-escola

  networks:
    apis-escola:
      driver: bridge
